<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('support_chats', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();

            // The Onwynd user who opened the chat (nullable for guest sessions)
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();

            // Guest session token for unauthenticated users
            $table->string('session_token')->nullable()->index();

            // Who is handling the chat
            // 'ai'      → AI bot is responding
            // 'waiting' → AI paused, waiting for human agent to claim
            // 'human'   → A human agent is responding
            // 'closed'  → Chat ended
            $table->enum('status', ['ai', 'waiting', 'human', 'closed'])->default('ai');

            // The agent who claimed the chat (null = AI handling it)
            $table->foreignId('assigned_agent_id')->nullable()->constrained('users')->nullOnDelete();

            // Timestamps for important state changes
            $table->timestamp('handover_requested_at')->nullable(); // User/AI flagged for human
            $table->timestamp('handover_at')->nullable();           // Agent actually claimed it
            $table->timestamp('first_response_at')->nullable();     // AI or agent first replied
            $table->timestamp('closed_at')->nullable();

            // Context pulled from Onwynd API at session start
            $table->json('user_context')->nullable();   // subscription, role, recent sessions…

            // Reference to the WyndChat live conversation (for real-time sync)
            $table->string('wyndchat_conversation_id')->nullable();

            $table->timestamps();
        });

        Schema::create('support_chat_messages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('chat_id')->constrained('support_chats')->cascadeOnDelete();

            // 'user'  → sent by the customer
            // 'ai'    → generated by the AI bot
            // 'agent' → sent by a human agent
            // 'system' → status change message (e.g., "Agent Alex has joined")
            $table->enum('sender_type', ['user', 'ai', 'agent', 'system'])->index();

            // The user or agent who sent it (null for AI / system messages)
            $table->foreignId('sender_id')->nullable()->constrained('users')->nullOnDelete();

            $table->text('message');
            $table->json('metadata')->nullable(); // attachments, language, model_used…
            $table->boolean('is_read')->default(false);

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('support_chat_messages');
        Schema::dropIfExists('support_chats');
    }
};
